//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materijal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materijal()
        {
            this.OcjenaMaterijal = new HashSet<OcjenaMaterijal>();
        }
    
        public int MaterijalId { get; set; }
        public string Naziv { get; set; }
        public int PredmetId { get; set; }
        public string Datum { get; set; }
        public Nullable<int> NastavnikId { get; set; }
        public string Sadrzaj { get; set; }
        public byte[] Fajl { get; set; }
        public string FajlIme { get; set; }
        public string FajlEkstenzija { get; set; }
    
        public virtual Nastavnik Nastavnik { get; set; }
        public virtual Predmet Predmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcjenaMaterijal> OcjenaMaterijal { get; set; }
    }
}
