//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavijest
    {
        public int ObavijestId { get; set; }
        public string Naslov { get; set; }
        public string Sadrzaj { get; set; }
        public int NastavnikId { get; set; }
        public int PredmetId { get; set; }
        public string Datum { get; set; }
    
        public virtual Nastavnik Nastavnik { get; set; }
        public virtual Predmet Predmet { get; set; }
    }
}
