//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RasporedCasova
    {
        public int RasporedCasovaId { get; set; }
        public int RazredId { get; set; }
        public string Pon { get; set; }
        public string Uto { get; set; }
        public string Sri { get; set; }
        public string Cet { get; set; }
        public string Pet { get; set; }
    
        public virtual Razred Razred { get; set; }
    }
}
